version: "3"
services:

  metabase-app:
    image: metabase/metabase
    container_name: metabase-app
    restart: always
    ports:
      - 3001:3000
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase_app
      MB_DB_PORT: 5432
      MB_DB_USER: metabase
      MB_DB_PASS: metabase
      MB_DB_HOST: postgres-db
    depends_on:
      - postgres-db
    links:
      - postgres-db

  postgres-db:
    container_name: postgres-db
    image: postgres:10-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    command:
      - bash
      - -c
      - |
        echo "Starting Postgres..."
        docker-entrypoint.sh -c 'shared_buffers=256MB' -c 'max_connections=200' -c 'wal_level=logical' -c 'max_wal_senders=5' -c 'max_replication_slots=3' -c 'log_statement=all' -c 'log_destination=stderr' -c 'log_statement=all' &
        echo "-- sleeping for 5 seconds to allow postgres to start before creating the metabase database..."
        sleep 5
        echo ".. Precreating postgres database Metabase"
        echo "CREATE DATABASE metabase_app;"            
        psql --username=postgres --dbname=postgres -c "CREATE DATABASE metabase_app;"            
        echo "CREATE ROLE metabase WITH PASSWORD 'metabase';"
        psql --username=postgres --dbname=postgres -c "CREATE ROLE metabase WITH PASSWORD 'metabase';"
        echo  "ALTER ROLE metabase LOGIN;"                
        psql --username=postgres --dbname=postgres -c "ALTER ROLE metabase LOGIN;"
        psql --username=postgres --dbname=postgres -c "ALTER ROLE metabase REPLICATION;"
        echo  "ALTER ROLE metabase SUPERUSER;"          
        psql --username=postgres --dbname=postgres -c "GRANT pg_read_server_files to metabase;"
        psql --username=postgres --dbname=postgres -c "ALTER ROLE metabase SUPERUSER;"          
        echo  "ALTER DATABASE metabase_app OWNER TO metabase;" 
        psql --username=postgres --dbname=postgres -c "ALTER DATABASE metabase_app OWNER TO metabase;" 
        #
        psql --username aws_user --dbname apac_redshift --password ${AWS_REDSHIFT_PASSWORD} --hostname ${AWS_REDSHIFT_HOSTNAME} --port 5439
        echo "--"
        sleep infinity

